on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Indicates if the file should be updated or not
        type: boolean
        required: false

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for new sdk version
        uses: xt0rted/dotnet-sdk-updater@testing
        id: sdk

      - name: Security label
        id: labels
        shell: bash
        run: |
          if [ '${{ steps.sdk.outputs.security }}' = 'true' ]
          then
            echo "::set-output name=security-label::security"
          fi

      - name: Create pull request
        if: steps.sdk.outputs.updated == 'true' && steps.sdk.outputs.dry-run == 'false'
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          signoff: true
          branch: "dependabot/nuget"
          branch-suffix: "dotnet-sdk-${{ steps.sdk.outputs.updated-version-to }}"
          delete-branch: true
          labels: |
            dependencies
            .NET
            ${{ steps.labels.outputs.security-label }}
          commit-message: |
            Bump dotnet sdk from ${{ steps.sdk.outputs.updated-version-from }} to ${{ steps.sdk.outputs.updated-version-to }}. ${{ steps.sdk.outputs.security ? '**This update includes a security fix.**' : '' }}"

            - [Release notes](https://github.com/dotnet/core/releases/tag/v${{ steps.sdk.outputs.updated-version-to }})
            - [Changelog](${{ steps.sdk.outputs.release-notes }})

            ---
            updated-dependencies:
            - dependency-name: dotnet-sdk
              dependency-type: direct:production
              update-type: version-update:${{ steps.sdk.outputs.update-type }}
            ...
          title: |
            Bump dotnet sdk from ${{ steps.sdk.outputs.updated-version-from }} to ${{ steps.sdk.outputs.updated-version-to }}
          body: |
            Bumps [dotnet sdk](https://github.com/dotnet/sdk) from ${{ steps.sdk.outputs.updated-version-from }} to ${{ steps.sdk.outputs.updated-version-to }}". ${{ steps.sdk.outputs.security ? '**This update includes a security fix.**' : '' }}"

            - [Release notes](https://github.com/dotnet/core/releases/tag/v${{ steps.sdk.outputs.updated-version-to }})
            - [Changelog](${{ steps.sdk.outputs.release-notes }})

      - name: Dump steps context
        if: always()
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
